### ISSUE TITLE
Cenário 1 - Mudança na regra na execução da operação de débito

### ISSUE THREAD

**Issue by ronimour** [gerencia-configuracao-mudanca/banco-gcm#1]
[solicitante] Cliente A001 

[descrição] O saldo mínimo em conta deverá ser R$ 2,00. Esta restrição deve ser informada ao usuário através de mensagem caso o valor a ser debitado ultrapasse o saldo mínimo em conta.

[impactos]
- positivos: 
  - menos gasto com operações com valores monetários baixos.
- negativos: 
  - gasto com operações com valores monetários baixos.
- não implementação: 
  - continuidade dos gastos.

[dependências] Não há

**Comment by masterprojectrn** [comment]
[análise de impacto] 
a mudança não terá uma custo alto e baixa complexidade. Pode ser feita e não apresenta impactos.

**Comment by ccmmaster** [comment]
[aprovação] Funcionalidade aprovada pelo comite de configuracao e mudanca.

**Comment by masterprojectrn** [comment]
[atribuição] Tarefa de implementar a funcionalidade atribuída a @silastiago

**Comment by silastiago** [comment]
[definição de escopo]
[cronograma]

```
Vai precisar ser alterado na regra de negócio da operação de debito, para que ela satisfaça o requisito de ter no minimo 2 reais de saldo para fazer esta operação. 
```

[deadline] entrega dia 02-05-2015.

**Comment by silastiago** [comment]
[implementação concluída]
- implentação finalizada;
- branch cenario1;
- pull request #8

**Comment by ronimour** [comment]
[controle de qualidade]
- testada;
- validada;

**Comment by masterprojectrn** [comment]
[integração]
- integração realizada com sucesso;
- criação da release R01.03.00 <a>https://github.com/gerencia-configuracao-mudanca/banco-gcm/releases/tag/R01.03.00</a>
