### ISSUE TITLE
Integração do Projeto com maven.

### ISSUE THREAD

**Issue by silastiago** [gerencia-configuracao-mudanca/banco-gcm#13]
[solicitante] Gerente de Projeto

[descrição] Foi pedido para equipe de desenvolvimento a implantação do maven no projeto do banco.

[impactos]

```
* positivos:
    * Praticidade na automatização das builds.
* negativos:
    * Reconfiguração do projeto para se adequar ao maven.
* não implementação:
    * builds continuarão manuais.
```

[dependências] Não há

**Comment by masterprojectrn** [comment]
[análise de impacto]
A mudança terá uma custo moderado e complexidade media. Apesar de existir um risco iminente a implantação do maven é essencial para as construções das builds automatizadas.

**Comment by masterprojectrn** [comment]
[atribuição] Tarefa de implementar a funcionalidade atribuída a @silastiago.

**Comment by silastiago** [comment]
[definição de escopo]
[cronograma]

Preciso criar arquivo pom.xml na raiz do projeto e configurar o maven.

[deadline] entrega dia 13-06-2015.

**Comment by silastiago** [comment]
[implementação concluída]

```
implentação finalizada;
branch maven;
pull request #14 
```

**Comment by josielmoreira** [comment]
[controle de qualidade]

testada;
validada

**Comment by masterprojectrn** [comment]
[integração]

```
integração realizada com sucesso;
criação da versão estavel T04.05.01 https://github.com/gerencia-configuracao-mudanca/banco-gcm/releases/tag/T04.05.01
```
