### ISSUE TITLE
Cenário 2.a - Alteração da operação de crédito: informar descrição da operação

### ISSUE THREAD

**Issue by ronimour** [gerencia-configuracao-mudanca/banco-gcm#2]
[solicitante] Cliente X001 

[descrição] Alteração na operação de crédito para que seja informada uma descrição para a operação.

[impactos]
- positivos: 
  -  aumento da usabilidade;
  -  redução na possibilidade de erro na execução da operação.
- negativos: 
  - não há
- não implementação: 
  -  risco do usuário cometer erros ao executar a operação de crédito.

[dependências] Não há

**Comment by masterprojectrn** [comment]
[analise de impacto] a mudança não trará grandes impactos para o sistema e tem uma complexidade baixa. Exigirá alterações em poucos artefatos do sistema e pode ser feita em um curto espaço de tempo. Não necessita aprovação do CCM.

**Comment by masterprojectrn** [comment]
[atribuição] a tarefa está atribuida a @ronimour

**Comment by ronimour** [comment]
[definição de escopo]
[cronograma] incluir uma mensagem na operação e na view
[deadline] 02-05-2015

**Comment by ronimour** [comment]
[implementação concluída] 
- implentação finalizada;
- branch cenario2a;
- pull request #7

**Comment by silastiago** [comment]
[implementação concluída]

    implentação finalizada;
    branch cenario1;
    pull request #8

**Comment by josielmoreira** [comment]
[controle de qualidade]

testada;
validada

**Comment by masterprojectrn** [comment]
[integração]

integração realizada com sucesso;
release que inclui essa mudança R01.03.01 https://github.com/gerencia-configuracao-mudanca/banco-gcm/releases/tag/R01.03.01
