### ISSUE TITLE
Cenário 2.b - Alteração da operação de débito: informar descrição da operação

### ISSUE THREAD

**Issue by ronimour** [gerencia-configuracao-mudanca/banco-gcm#3]
[solicitante] Cliente Y001 

[descrição] Alteração na operação de débito para que seja informada uma descrição para a operação.

[impactos]
- positivos: 
  -  aumento da usabilidade;
  -  redução na possibilidade de erro na execução da operação.
- negativos: 
  - não há
- não implementação: 
  -  risco do usuário cometer erros ao executar a operação de débito.

[dependências] Não há

**Comment by masterprojectrn** [comment]
[analise de impacto] a mudança não trará grandes impactos para o sistema e tem uma complexidade baixa. Exigirá alterações em poucos artefatos do sistema e pode ser feita em um curto espaço de tempo. Não necessita aprovação do CCM.

**Comment by masterprojectrn** [comment]
[atribuição] a tarefa está atribuida a @josielmoreira

**Comment by josielmoreira** [comment]
[definição de escopo]
[cronograma] incluir uma mensagem na operação e na view
[deadline] 02-05-2015

**Comment by josielmoreira** [comment]
[implementação concluída]
- implentação finalizada;
- branch cenario2b;
- pull request cenario2a finalizado #9

**Comment by ronimour** [comment]
[controle de qualidade]
- testada;
- validada.

**Comment by masterprojectrn** [comment]
[integração]
- integração realizada com sucesso;
- release que inclui essa mudança R01.03.01 <a>https://github.com/gerencia-configuracao-mudanca/banco-gcm/releases/tag/R01.03.01</a>
