### ISSUE TITLE
Cenário 3 - Bug na funcionalidade bônus

### ISSUE THREAD

**Issue by ronimour** [gerencia-configuracao-mudanca/banco-gcm#4]
[solicitante] Analista de negócio AN001

[descrição] Alteração do bônus para 3% do valor de cada operação.

[impactos]
- positivos: 
  - maior satisfação do cliente do banco
- negativos 
  - não há
- não implementação
  - não há

[dependências] não há

**Comment by masterprojectrn** [comment]
[analise de impacto] Mudança para corrigir erro. Alteração de baixa complexidade e baixo risco. Não necessita aprovação do CCM.

**Comment by masterprojectrn** [comment]
[atribuição] atribuido a @josielmoreira

**Comment by josielmoreira** [comment]
[definição de escopo]
[cronograma] corrigir um bug na operação de bônus
[deadline] 02-05-2015

**Comment by josielmoreira** [comment]
[implementação concluída]
- implentação finalizada;
- branch cenario3;
- pull request #10

**Comment by ronimour** [comment]
[controle de qualidade]
- testada.
- validada

**Comment by masterprojectrn** [comment]
[integração]
- mudança integrada com sucesso!
- release criada R01.03.01 https://github.com/gerencia-configuracao-mudanca/banco-gcm/releases/tag/R01.03.00
