### ISSUE TITLE
Cenário 4 - Crédito em Poupança

### ISSUE THREAD

**Issue by ronimour** [gerencia-configuracao-mudanca/banco-gcm#5]
[solicitante] Cliente Z

[descrição] O sistema deve permitir o crédito em poupança.

[impactos]
- positivos:  
  - o cliente vai poder creditar em poupança.
- negativos: 
  - não existe
- não implementação: 
  - insatisfação do cliente

[dependências] não há

**Comment by masterprojectrn** [comment]
[analise de impacto] A mudança afetará classes importantes do sistema, que terão que ser alteradas. Também será feita alterações em outras classes do sistema. O banco de dados também terá que ser alterado. O que pode ocasionar falhas em outras partes do sistema.

**Comment by ccmmaster** [comment]
[aprovação] a mudança pode ser feita.

**Comment by masterprojectrn** [comment]
[atribuição] Tarefa de implementar a funcionalidade sob responsabilidade de @silastiago

**Comment by silastiago** [comment]
[definição de escopo]
[cronograma]

Vai precisar ser alterado na regra de negócio da operação de credito e o banco de dados, para que ela satisfaça o requisito de creditar em conta poupanca. 

[deadline] entrega dia 02-05-2015.

**Comment by silastiago** [comment]
[implementação concluída]
- implementação finalizada;
- branch cenario4;
- pull request #11

**Comment by josielmoreira** [comment]
[controle de qualidade]
- testada.
- validada

**Comment by masterprojectrn** [comment]
[integração]
- mudança integrada com sucesso;
- release criada R01.04.00 https://github.com/gerencia-configuracao-mudanca/banco-gcm/releases/tag/R01.04.00
