### ISSUE TITLE
Cenário 5 - Mensagem ao efetuar o crédito em poupança

### ISSUE THREAD

**Issue by ronimour** [gerencia-configuracao-mudanca/banco-gcm#6]
[solicitante] Analista de usabilidade

[descrição] ao efetuar a operação de crédito em poupança deve-se mostrar a seguinte mensagem: 
"Crédito no valor XX para a conta YY realizado com sucesso"

[impactos]
- positivos:  
  - aumento da usabilidade
- negativos: 
  - não há
- não implementação: 
  -  falta de feedback

[dependências] depende da implementação do crédito em poupança.

**Comment by masterprojectrn** [comment]
[análise de impacto] a mudança pode ser feita, sem necessidade da aprovação do CCM.

**Comment by masterprojectrn** [comment]
[atribuição] mudança sob a responsabilidade de @ronimour

**Comment by ronimour** [comment]
[definição de escopo]

[cronograma] 
- colocar uma mensagem na classe da operação;
- mostrar essa mensagem na view;

[deadline] 02-05-2015

**Comment by ronimour** [comment]
[implementação concluída]
- implementação finalizada;
- branch cenario5_final;
- pull request #12

**Comment by masterprojectrn** [comment]
[controle de qualidade]
- testada;
- falhou na validação;
  [comentário]
- a mensagem que deve ser mostrado é a seguinte: “Crédito no valor XX para a poupança YY foi realizado com sucesso”.

**Comment by ronimour** [comment]
[reimplementando]

[deadline] 02-05-2015

**Comment by ronimour** [comment]
[reimplementação concluída]

reimplementação finalizada;
branch cenario5_final;
pull request #12

**Comment by masterprojectrn** [comment]
[controle de qualidade]
- validada

**Comment by masterprojectrn** [comment]
[integração]
- integração realizada com sucesso;
- release criada R01.04.01 https://github.com/gerencia-configuracao-mudanca/banco-gcm/releases/tag/R01.04.01
